apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: database
spec:
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
