apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: vms-namespace
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=     
  POSTGRES_PASSWORD: aGlldWxpbmh0cmFuZw==   
  POSTGRES_DB: dm1z      
