apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: vms-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: "008971665624.dkr.ecr.ap-east-1.amazonaws.com/minio"
        env:
          - name: MINIO_ACCESS_KEY
            value: "myacceskey"        # Hoặc có thể lấy từ ConfigMap/Secret
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: vms-secret
                key: APP_MINIO_SECRET_ACCESS_KEY
        ports:
          - containerPort: 9000
        volumeMounts:
          - name: minio-data
            mountPath: "/data"
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-pvc
