apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  namespace: vms-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@example.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "adminpassword"
        ports:
        - containerPort: 80
