apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 10Gi  # Chỉnh sửa dung lượng phù hợp với yêu cầu của bạn
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  awsElasticBlockStore:
    volumeID: postgrest-pv  # Đặt volume ID của EBS volume của bạn
