apiVersion: v1
kind: ConfigMap
metadata:
  name: vms-fe-config
  namespace: vms-namespace
data:
  NEXT_PUBLIC_API_BASE_URL: "http://vms-be.vms-namespace.svc.cluster.local" 
  NEXT_PUBLIC_JWT_EXPIRATION: 5m
  NEXT_PUBLIC_JWT_SECRET: dd5f3089-40c3-403d-af14-d0c228b05cb4
  NEXT_PUBLIC_JWT_REFRESH_TOKEN_SECRET: 7c4c1c50-3230-45bf-9eae-c9b2e401c767
  NEXT_PUBLIC_VERSION: 'v0'
  NEXT_PUBLIC_API_HOST: "http://vms-be.vms-namespace.svc.cluster.local:10000"
  NEXT_PUBLIC_SOCKET_CCTT: "ws://http://vms-be.vms-namespace.svc.cluster.local:10000"
  NEXT_PUBLIC_API_SBS: "http://vms-be.vms-namespace.svc.cluster.local:10000"
  NEXT_PUBLIC_BYPASS_AUTH: "true"
  NEXT_PUBLIC_SERVER: "vms-be.vms-namespace.svc.cluster.local"
