apiVersion: apps/v1
kind: Deployment
metadata:
  name: vms-fe
  namespace: vms-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vms-fe
  template:
    metadata:
      labels:
        app: vms-fe
    spec:
      containers:
      - name: vms-fe
        image: "vmslab1/vmsfeprune"
        
        envFrom:
          - configMapRef:
              name: vms-fe-config  # Tham chiếu đến ConfigMap vms-fe-config
        ports:
          - containerPort: 3000
