apiVersion: v1
kind: Secret
metadata:
  name: vms-secret
  namespace: vms-namespace
type: Opaque
data:
  APP_SQL_USER: "cG9zdGdyZXM="
  APP_SQL_PASSWORD: "aGlldWxpbmh0cmFuZw=="
  APP_MINIO_SECRET_ACCESS_KEY: "bXlhY2Nlc3NrZXk="
  APP_MINIO_ENDPOINT: "bWluaW8tc2VydmljZS5taW5pby5zdmMuY2x1c3Rlci5sb2NhbA=="  # Tên service của MinIO
  APP_MINIO_ACCESSKEY_ID: "bXlzZWNyZXRrZXk="
