apiVersion: v1
kind: Service
metadata:
  name: vms-be
  namespace: vms-namespace
spec:
  
  selector:
    app: vms-be
  ports:
    - name: http
      port: 10000
      targetPort: 10000
      protocol: TCP
  type: LoadBalancer
