apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: vms-namespace
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      nodePort: 30000
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 30001

