apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  MINIO_ROOT_USER: YWRtaW4=        # "admin" (base64)
  MINIO_ROOT_PASSWORD: aGlldWxpbmh0cmFuZw==   # "hieulinhtrang" (base64)


