apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_PASSWORD
          ports:
            - containerPort: 9000
              name: api
              protocol: TCP
              hostPort: 9000
            - containerPort: 9001
              name: webui
              protocol: TCP
              hostPort: 9001
          volumeMounts:
            - name: minio-data
              mountPath: /data/minio
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-pvc


