apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio
type: Opaque
data:
  MINIO_ACCESS_KEY: bXlhY2Nlc3NrZXk=  # "myaccesskey" (base64 encoded)
  MINIO_SECRET_KEY: bXlzZWNyZXRrZXk=  # "mysecretkey" (base64 encoded)
